org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home
android.jetifier.ignorelist=androidx.window.extensions,androidx.window.sidecar
kotlin.incremental.useClasspathSnapshot=false
android.defaults.buildfeatures.buildconfig=true